"""Initial migration.

Revision ID: 4e1d871dcffc
Revises: 
Create Date: 2021-02-17 21:25:18.434054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e1d871dcffc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memes', sa.Column('bottom_text', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memes', 'bottom_text')
    # ### end Alembic commands ###
